[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  timeout = 30  # Увеличиваем таймаут для медленных ИИ-ответов