[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Настройка таймаута для функции check-text
[functions.check-text]
  timeout = 30